# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#94e2d5" }

# Hovered
hovered         = { fg = "#1e1e2e", bg = "#89b4fa" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#f9e2af", italic = true }
find_position = { fg = "#f5c2e7", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#a6e3a1", bg = "#a6e3a1" }
marker_copied   = { fg = "#f9e2af", bg = "#f9e2af" }
marker_cut      = { fg = "#f38ba8", bg = "#f38ba8" }

# Tab
tab_active   = { fg = "#1e1e2e", bg = "#89b4fa" }
tab_inactive = { fg = "#cdd6f4", bg = "#45475a" }
tab_width    = 1

# Border
border_symbol = "â”‚"
border_style  = { fg = "#7f849c" }

# Highlighting
syntect_theme = "~/.config/yazi/Catppuccin-mocha.tmTheme"

# : }}}


# : Status {{{

[status]
separator_open  = "î‚¶"
separator_close = "î‚´"
separator_style = { fg = "#45475a", bg = "#45475a" }

# Mode
mode_normal = { fg = "#1e1e2e", bg = "#89b4fa", bold = true }
mode_select = { fg = "#1e1e2e", bg = "#a6e3a1", bold = true }
mode_unset  = { fg = "#1e1e2e", bg = "#f2cdcd", bold = true }

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#89b4fa", bg = "#45475a" }
progress_error  = { fg = "#f38ba8", bg = "#45475a" }

# Permissions
permissions_t = { fg = "#89b4fa" }
permissions_r = { fg = "#f9e2af" }
permissions_w = { fg = "#f38ba8" }
permissions_x = { fg = "#a6e3a1" }
permissions_s = { fg = "#7f849c" }

# : }}}


# : Input {{{

[input]
border   = { fg = "#89b4fa" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border   = { fg = "#89b4fa" }
active   = { fg = "#f5c2e7" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#89b4fa" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#313244" }
cand            = { fg = "#94e2d5" }
rest            = { fg = "#9399b2" }
desc            = { fg = "#f5c2e7" }
separator       = " îªœ "
separator_style = { fg = "#585b70" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#f5c2e7" }
run     = { fg = "#94e2d5" }
desc    = { fg = "#9399b2" }
hovered = { bg = "#585b70", bold = true }
footer  = { fg = "#45475a", bg = "#cdd6f4" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#94e2d5" },

	# Videos
	{ mime = "video/*", fg = "#f9e2af" },
	{ mime = "audio/*", fg = "#f9e2af" },

	# Archives
	{ mime = "application/zip",             fg = "#f5c2e7" },
	{ mime = "application/gzip",            fg = "#f5c2e7" },
	{ mime = "application/x-tar",           fg = "#f5c2e7" },
	{ mime = "application/x-bzip",          fg = "#f5c2e7" },
	{ mime = "application/x-bzip2",         fg = "#f5c2e7" },
	{ mime = "application/x-7z-compressed", fg = "#f5c2e7" },
	{ mime = "application/x-rar",           fg = "#f5c2e7" },

	# Fallback
	{ name = "*", fg = "#cdd6f4" },
	{ name = "*/", fg = "#89b4fa" }
]

# : }}}


# : Icons {{{

[icons]
rules = [
  { name = "di", text = "ğŸ“"}, 
  { name = "fi", text = "ğŸ“ƒ"}, 
  { name = "tw", text = "ğŸ¤"}, 
  { name = "ow", text = "ğŸ“‚"}, 
  { name = "ln", text = "â›“"}, 
  { name = "or", text = "âŒ"}, 
  { name = "ex", text = "ğŸ¯"}, 
  { name = "*.txt", text = "âœ"}, 
  { name = "*.mom", text = "âœ"}, 
  { name = "*.me", text = "âœ"}, 
  { name = "*.ms", text = "âœ"}, 
  { name = "*.avif", text = "ğŸ–¼"}, 
  { name = "*.png", text = "ğŸ–¼"}, 
  { name = "*.webp", text = "ğŸ–¼"}, 
  { name = "*.ico", text = "ğŸ–¼"}, 
  { name = "*.jpg", text = "ğŸ“¸"}, 
  { name = "*.jpe", text = "ğŸ“¸"}, 
  { name = "*.jpeg", text = "ğŸ“¸"}, 
  { name = "*.gif", text = "ğŸ–¼"}, 
  { name = "*.svg", text = "ğŸ—º"}, 
  { name = "*.tif", text = "ğŸ–¼"}, 
  { name = "*.tiff", text = "ğŸ–¼"}, 
  { name = "*.xcf", text = "ğŸ–Œ"}, 
  { name = "*.html", text = "ğŸŒ"}, 
  { name = "*.xml", text = "ğŸ“°"}, 
  { name = "*.gpg", text = "ğŸ”’"}, 
  { name = "*.css", text = "ğŸ¨"}, 
  { name = "*.pdf", text = "ğŸ“š"}, 
  { name = "*.djvu", text = "ğŸ“š"}, 
  { name = "*.epub", text = "ğŸ“š"}, 
  { name = "*.csv", text = "ğŸ““"}, 
  { name = "*.xlsx", text = "ğŸ““"}, 
  { name = "*.tex", text = "ğŸ“œ"},
	{ name = "di", text = "ğŸ“"}, 
	{ name = "fi", text = "ğŸ“ƒ"}, 
	{ name = "tw", text = "ğŸ¤"}, 
	{ name = "ow", text = "ğŸ“‚"}, 
	{ name = "ln", text = "â›“"}, 
	{ name = "or", text = "âŒ"}, 
	{ name = "ex", text = "ğŸ¯"}, 
	{ name = "*.txt", text = "âœ"}, 
	{ name = "*.mom", text = "âœ"}, 
	{ name = "*.me", text = "âœ"}, 
	{ name = "*.ms", text = "âœ"}, 
	{ name = "*.avif", text = "ğŸ–¼"}, 
	{ name = "*.png", text = "ğŸ–¼"}, 
	{ name = "*.webp", text = "ğŸ–¼"}, 
	{ name = "*.ico", text = "ğŸ–¼"}, 
	{ name = "*.jpg", text = "ğŸ“¸"}, 
	{ name = "*.jpe", text = "ğŸ“¸"}, 
	{ name = "*.jpeg", text = "ğŸ“¸"}, 
	{ name = "*.gif", text = "ğŸ–¼"}, 
	{ name = "*.svg", text = "ğŸ—º"}, 
	{ name = "*.tif", text = "ğŸ–¼"}, 
	{ name = "*.tiff", text = "ğŸ–¼"}, 
	{ name = "*.xcf", text = "ğŸ–Œ"}, 
	{ name = "*.html", text = "ğŸŒ"}, 
	{ name = "*.xml", text = "ğŸ“°"}, 
	{ name = "*.gpg", text = "ğŸ”’"}, 
	{ name = "*.css", text = "ğŸ¨"}, 
	{ name = "*.pdf", text = "ğŸ“š"}, 
	{ name = "*.djvu", text = "ğŸ“š"}, 
	{ name = "*.epub", text = "ğŸ“š"}, 
	{ name = "*.csv", text = "ğŸ““"}, 
	{ name = "*.xlsx", text = "ğŸ““"}, 
	{ name = "*.tex", text = "ğŸ“œ"}, 
	{ name = "*.md", text = "ğŸ“˜"}, 
	{ name = "*.r", text = "ğŸ“Š"}, 
	{ name = "*.R", text = "ğŸ“Š"}, 
	{ name = "*.rmd", text = "ğŸ“Š"}, 
	{ name = "*.Rmd", text = "ğŸ“Š"}, 
	{ name = "*.m", text = "ğŸ“Š"}, 
	{ name = "*.mp3", text = "ğŸµ"}, 
	{ name = "*.opus", text = "ğŸµ"}, 
	{ name = "*.ogg", text = "ğŸµ"}, 
	{ name = "*.m4a", text = "ğŸµ"}, 
	{ name = "*.flac", text = "ğŸ¼"}, 
	{ name = "*.wav", text = "ğŸ¼"}, 
	{ name = "*.mkv", text = "ğŸ¥"}, 
	{ name = "*.mp4", text = "ğŸ¥"}, 
	{ name = "*.webm", text = "ğŸ¥"}, 
	{ name = "*.mpeg", text = "ğŸ¥"}, 
	{ name = "*.avi", text = "ğŸ¥"}, 
	{ name = "*.mov", text = "ğŸ¥"}, 
	{ name = "*.mpg", text = "ğŸ¥"}, 
	{ name = "*.wmv", text = "ğŸ¥"}, 
	{ name = "*.m4b", text = "ğŸ¥"}, 
	{ name = "*.flv", text = "ğŸ¥"}, 
	{ name = "*.zip", text = "ğŸ“¦"}, 
	{ name = "*.rar", text = "ğŸ“¦"}, 
	{ name = "*.7z", text = "ğŸ“¦"}, 
	{ name = "*.tar", text = "ğŸ“¦"}, 
	{ name = "*.z64", text = "ğŸ®"}, 
	{ name = "*.v64", text = "ğŸ®"}, 
	{ name = "*.n64", text = "ğŸ®"}, 
	{ name = "*.gba", text = "ğŸ®"}, 
	{ name = "*.nes", text = "ğŸ®"}, 
	{ name = "*.gdi", text = "ğŸ®"}, 
	{ name = "*.1", text = "â„¹"}, 
	{ name = "*.nfo", text = "â„¹"}, 
	{ name = "*.info", text = "â„¹"}, 
	{ name = "*.log", text = "ğŸ“™"}, 
	{ name = "*.iso", text = "ğŸ“€"}, 
	{ name = "*.img", text = "ğŸ“€"},
	{ name = "*.bib", text = "ğŸ“"},
	{ name = "*.ged", text = "ğŸ‘ª"},
	{ name = "*.part", text = "ğŸ’”"},
	{ name = "*.torrent", text = "ğŸ”½"},
	{ name = "*.jar", text = "â™¨"},
	{ name = "*.java", text = "â™¨"}, 
  ]
# : }}}
